### ISSUE TITLE
mobile phone header ad revisions

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-okwatch#1]
> Would your team be able to customize our site so that our logo, as well as any Doubleclick banner ad, is displayed on mobile?

- [ ] CSS to don't hide main header on mobile
- [ ] CSS to don't hide header ad widget on mobile

Questions:

- [x] is this just on the homepage, or elsewhere as well? Assuming elsewhere for now.

**Comment by julia-smith** [comment]
Yep, let's make it global.

**Comment by benlk** [comment]
Demo is live here: http://okwatch.staging.wpengine.com/

DFP ads are set up but not running on staging; I've created some placeholders with leftover images from a Rivard thing.

If they're okay with how that performs, I'll deploy it to production.

**Comment by benlk** [comment]
Resolved with 078ad94965879fa096db4db33bd4eafecdd4798e...3128b2b5c4c3aa98df7e5f5ae1f9e4929dc927d0
