### ISSUE TITLE
Fix desktop ad display

### ISSUE THREAD

**Issue by julia-smith** [INN/umbrella-okwatch#3]
Please investigate this report from the client:

> Is the team still working on Doubleclick ads appearing on  mobile? I assume so because the DB ads just stopped displaying on desktop.

**Comment by benlk** [comment]
http://oklahomawatch.org/?googfc is saying "Ad unit failed to fetch" for all ads, I don't think I can troubleshoot further without access to their DFP account as everything seems to be working as intended browser-side, and delivery diagnostics requires access to their account.

**Comment by benlk** [comment]
They should make sure they have ads with creatives in the following ad units *and* sizes:

- leaderboard, 728x90
- Mobile_Banner, 320x50
- sidebar-med-rect-1, 300x250
